-- Denylashes starter catalog.
-- Run after schema.sql. Existing rows are updated by slug.

insert into public.products (
  slug,
  title,
  price_cents,
  currency,
  category,
  type,
  short_desc,
  description,
  image_url,
  is_active,
  created_at
)
values
  (
    'angel-lashes-mix-tray',
    'Angel Lashes Mix Tray',
    1200,
    'EUR',
    'Lashes',
    'physical',
    'Soft brown mix tray for airy, feathered volume.',
    'A curated mix of lengths for a seamless, wispy set. Lightweight fibers and a smooth finish.',
    '/images/product-1.svg',
    true,
    '2026-01-05T10:00:00Z'
  ),
  (
    'brow-wax-tint-course',
    'Brow Wax & Tint Masterclass',
    5000,
    'EUR',
    'Courses',
    'digital',
    'Online course for polished, long-lasting brows.',
    'Step-by-step lessons covering mapping, tinting, and aftercare for salon-grade results.',
    '/images/product-2.svg',
    true,
    '2026-01-10T10:00:00Z'
  ),
  (
    'classic-brown-lashes-020-d',
    'Classic Brown Lashes 0.20 D Curl',
    1200,
    'EUR',
    'Lashes',
    'physical',
    'Rich brown classics with a soft, natural lift.',
    'Premium fibers with consistent curl and effortless pickup for classic sets.',
    '/images/product-3.svg',
    true,
    '2026-01-12T10:00:00Z'
  ),
  (
    'brown-mix-tray-05-d',
    'Brown Mix Lash Trays 0.5 D Curl',
    1200,
    'EUR',
    'Lashes',
    'physical',
    'Balanced curl for soft volume and definition.',
    'Mixed lengths for effortless mapping, perfect for natural brown lash sets.',
    '/images/product-4.svg',
    true,
    '2026-01-16T10:00:00Z'
  ),
  (
    'precision-tweezer-set',
    'Precision Tweezer Set',
    2900,
    'EUR',
    'Tools',
    'physical',
    'Two-piece set for flawless isolation and pickup.',
    'Lightweight steel tweezers with micro-grip tips for precision control.',
    '/images/product-1.svg',
    true,
    '2026-01-18T10:00:00Z'
  ),
  (
    'silk-lash-adhesive',
    'Silk Lash Adhesive',
    2400,
    'EUR',
    'Liquids',
    'physical',
    'Fast-drying adhesive with a flexible bond.',
    'Humidity-balanced formula with smooth viscosity for seamless application.',
    '/images/product-2.svg',
    true,
    '2026-01-20T10:00:00Z'
  ),
  (
    'volume-fan-guide',
    'Volume Fan Guide (E-Book)',
    1800,
    'EUR',
    'E-Books',
    'digital',
    'Digital guide to mastering symmetrical volume fans.',
    'Illustrated techniques, troubleshooting, and practice drills for volume sets.',
    '/images/product-3.svg',
    true,
    '2026-01-22T10:00:00Z'
  ),
  (
    'lash-cleanser-foam',
    'Lash Cleanser Foam',
    1600,
    'EUR',
    'Liquids',
    'physical',
    'Gentle daily cleanser for fresh, healthy lashes.',
    'Oil-free foam cleanser to remove buildup and extend retention.',
    '/images/product-4.svg',
    true,
    '2026-01-24T10:00:00Z'
  ),
  (
    'hybrid-mapping-kit',
    'Hybrid Mapping Kit',
    3600,
    'EUR',
    'Tools',
    'physical',
    'Everything you need to map hybrid sets.',
    'Includes mapping pads, pens, and guide cards for consistent results.',
    '/images/product-1.svg',
    true,
    '2026-01-26T10:00:00Z'
  ),
  (
    'lash-lift-course',
    'Lash Lift Certification Course',
    7200,
    'EUR',
    'Courses',
    'digital',
    'Comprehensive lash lift theory and technique.',
    'Video modules, technique charts, and aftercare guidance for perfect lifts.',
    '/images/product-2.svg',
    true,
    '2026-01-28T10:00:00Z'
  ),
  (
    'micro-brush-pack',
    'Micro Brush Pack',
    900,
    'EUR',
    'Tools',
    'physical',
    'Lint-free brushes for precise cleanup.',
    'Multi-size micro brushes for adhesive removal and detailed corrections.',
    '/images/product-3.svg',
    true,
    '2026-01-30T10:00:00Z'
  ),
  (
    'lash-artist-starter-kit',
    'Lash Artist Starter Kit',
    14900,
    'EUR',
    'Lashes',
    'physical',
    'Premium kit for artists building their signature set.',
    'Curated lash trays, adhesive, prep, and tools packaged for studio success.',
    '/images/product-4.svg',
    true,
    '2026-02-01T10:00:00Z'
  )
on conflict (slug) do update
set
  title = excluded.title,
  price_cents = excluded.price_cents,
  currency = excluded.currency,
  category = excluded.category,
  type = excluded.type,
  short_desc = excluded.short_desc,
  description = excluded.description,
  image_url = excluded.image_url,
  is_active = excluded.is_active,
  created_at = excluded.created_at;
