import { Product } from "./types";

export const productsMock: Product[] = [
  {
    id: "mock-1",
    slug: "angel-lashes-mix-tray",
    title: "Angel Lashes Mix Tray",
    price_cents: 1200,
    currency: "EUR",
    category: "Lashes",
    type: "physical",
    short_desc: "Soft brown mix tray for airy, feathered volume.",
    description:
      "A curated mix of lengths for a seamless, wispy set. Lightweight fibers and a smooth finish.",
    image_url: "/images/product-1.svg",
    is_active: true,
    created_at: "2026-01-05T10:00:00Z",
  },
  {
    id: "mock-2",
    slug: "brow-wax-tint-course",
    title: "Brow Wax & Tint Masterclass",
    price_cents: 5000,
    currency: "EUR",
    category: "Courses",
    type: "digital",
    short_desc: "Online course for polished, long-lasting brows.",
    description:
      "Step-by-step lessons covering mapping, tinting, and aftercare for salon-grade results.",
    image_url: "/images/product-2.svg",
    is_active: true,
    created_at: "2026-01-10T10:00:00Z",
  },
  {
    id: "mock-3",
    slug: "classic-brown-lashes-020-d",
    title: "Classic Brown Lashes 0.20 D Curl",
    price_cents: 1200,
    currency: "EUR",
    category: "Lashes",
    type: "physical",
    short_desc: "Rich brown classics with a soft, natural lift.",
    description:
      "Premium fibers with consistent curl and effortless pickup for classic sets.",
    image_url: "/images/product-3.svg",
    is_active: true,
    created_at: "2026-01-12T10:00:00Z",
  },
  {
    id: "mock-4",
    slug: "brown-mix-tray-05-d",
    title: "Brown Mix Lash Trays 0.5 D Curl",
    price_cents: 1200,
    currency: "EUR",
    category: "Lashes",
    type: "physical",
    short_desc: "Balanced curl for soft volume and definition.",
    description:
      "Mixed lengths for effortless mapping, perfect for natural brown lash sets.",
    image_url: "/images/product-4.svg",
    is_active: true,
    created_at: "2026-01-16T10:00:00Z",
  },
  {
    id: "mock-5",
    slug: "precision-tweezer-set",
    title: "Precision Tweezer Set",
    price_cents: 2900,
    currency: "EUR",
    category: "Tools",
    type: "physical",
    short_desc: "Two-piece set for flawless isolation and pickup.",
    description:
      "Lightweight steel tweezers with micro-grip tips for precision control.",
    image_url: "/images/product-1.svg",
    is_active: true,
    created_at: "2026-01-18T10:00:00Z",
  },
  {
    id: "mock-6",
    slug: "silk-lash-adhesive",
    title: "Silk Lash Adhesive",
    price_cents: 2400,
    currency: "EUR",
    category: "Liquids",
    type: "physical",
    short_desc: "Fast-drying adhesive with a flexible bond.",
    description:
      "Humidity-balanced formula with smooth viscosity for seamless application.",
    image_url: "/images/product-2.svg",
    is_active: true,
    created_at: "2026-01-20T10:00:00Z",
  },
  {
    id: "mock-7",
    slug: "volume-fan-guide",
    title: "Volume Fan Guide (E-Book)",
    price_cents: 1800,
    currency: "EUR",
    category: "E-Books",
    type: "digital",
    short_desc: "Digital guide to mastering symmetrical volume fans.",
    description:
      "Illustrated techniques, troubleshooting, and practice drills for volume sets.",
    image_url: "/images/product-3.svg",
    is_active: true,
    created_at: "2026-01-22T10:00:00Z",
  },
  {
    id: "mock-8",
    slug: "lash-cleanser-foam",
    title: "Lash Cleanser Foam",
    price_cents: 1600,
    currency: "EUR",
    category: "Liquids",
    type: "physical",
    short_desc: "Gentle daily cleanser for fresh, healthy lashes.",
    description:
      "Oil-free foam cleanser to remove buildup and extend retention.",
    image_url: "/images/product-4.svg",
    is_active: true,
    created_at: "2026-01-24T10:00:00Z",
  },
  {
    id: "mock-9",
    slug: "hybrid-mapping-kit",
    title: "Hybrid Mapping Kit",
    price_cents: 3600,
    currency: "EUR",
    category: "Tools",
    type: "physical",
    short_desc: "Everything you need to map hybrid sets.",
    description:
      "Includes mapping pads, pens, and guide cards for consistent results.",
    image_url: "/images/product-1.svg",
    is_active: true,
    created_at: "2026-01-26T10:00:00Z",
  },
  {
    id: "mock-10",
    slug: "lash-lift-course",
    title: "Lash Lift Certification Course",
    price_cents: 7200,
    currency: "EUR",
    category: "Courses",
    type: "digital",
    short_desc: "Comprehensive lash lift theory and technique.",
    description:
      "Video modules, technique charts, and aftercare guidance for perfect lifts.",
    image_url: "/images/product-2.svg",
    is_active: true,
    created_at: "2026-01-28T10:00:00Z",
  },
  {
    id: "mock-11",
    slug: "micro-brush-pack",
    title: "Micro Brush Pack",
    price_cents: 900,
    currency: "EUR",
    category: "Tools",
    type: "physical",
    short_desc: "Lint-free brushes for precise cleanup.",
    description:
      "Multi-size micro brushes for adhesive removal and detailed corrections.",
    image_url: "/images/product-3.svg",
    is_active: true,
    created_at: "2026-01-30T10:00:00Z",
  },
  {
    id: "mock-12",
    slug: "lash-artist-starter-kit",
    title: "Lash Artist Starter Kit",
    price_cents: 14900,
    currency: "EUR",
    category: "Lashes",
    type: "physical",
    short_desc: "Premium kit for artists building their signature set.",
    description:
      "Curated lash trays, adhesive, prep, and tools packaged for studio success.",
    image_url: "/images/product-4.svg",
    is_active: true,
    created_at: "2026-02-01T10:00:00Z",
  },
];


